[package]
name = "gaugemc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = ">=1.5"
num-traits = ">=0.2"
ndarray-rand = ">=0.14"

[dependencies.ndarray]
version = ">= 0.13"
features = ["rayon"]