[package]
name = "gaugemc"
version = "1.0.0"
edition = "2021"

[features]
default = ["gpu-cuda", "hashbrown-hashing"]
gpu-cuda = ["cudarc"]
hashbrown-hashing = ["hashbrown"]

[dependencies]
rayon = "1.12"
num-traits = "0.2"
ndarray-rand = "0.16"
cudarc = { version = "0.19", optional = true, features = ["cuda-version-from-build-system"] }
hashbrown = { version = "0.17", optional = true }

[dependencies.ndarray]
version = "0.17"
features = ["rayon"]

[dev-dependencies]
env_logger = "0.11"
ndarray-npy = "0.10"
log = "0.4"
scilib = "1.0"
num-complex = "0.4"

[[example]]
name = "simple_cuda"
required-features = ["gpu-cuda"]

[[bench]]
name = "cpu_bench"

[[bench]]
name = "cuda_bench"
required-features = ["gpu-cuda"]